# Generated by Django 3.1.4 on 2021-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='noti_status',
            field=models.BooleanField(default=True),
        ),
    ]
