# Generated by Django 3.1.4 on 2021-04-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_noti_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='noti_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='noti_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
