# Generated by Django 3.1.4 on 2021-05-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
